### ISSUE TITLE
ExpressionDebugger does not seem to work with NetFramework

### ISSUE THREAD

**Issue by taxophobia** [chaowlert/ExpressionDebugger#1]
There seems to be a easy to remedy incompability that keeps ExpressionDebugger from working with NetFramework. In file "ExpressionDebugger\ExpressionCompiler" the function "LoadFromStream" pulls in a depedendency on "System.Runtime.Loader" that is not avaible and will not be avaible in NetFramework. It is trivally replaced:

`return AssemblyLoadContext.Default.LoadFromStream(assemblyStream, symbolsStream);`
becomes 
`return System.Reflection.Assembly.Load(assemblyStream.ToArray(), symbolsStream.ToArray());`

With this change there ExpressionDebugger will run without complaining about missing assemblies and fail on

`references.Add(Assembly.Load(new AssemblyName("System.Runtime")));
references.Add(Assembly.Load(new AssemblyName("System.Collections")));`

in the same file. It seems to work ok after commenting out these two lines. But I doubt thats a proper fix.

Besides this minor problem I am very contend user of ExpressionDebugger (1.x until now) and Mapster (3.x until now). Keep going and please ask for any needed clarification on my side.

**Comment by chaowlert** [comment]
Thank you for report. LoadFromStream is part of net standard, so I use without proper testing.

I will take a look on this weekend.
